'$schema' = "node_modules/wrangler/config-schema.json"

name = "manifest-editor"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"
assets.directory = ".open-next/assets"
assets.binding = "ASSETS"
account_id = "ae784157f30fd7164f22b075991c1caa"
kv_namespaces = [
    { binding = "PREVIEW_KV", id = "9708730cddd545a68d255f11fe2d6b89" },
]

[observability.logs]
enabled = true

[vars]
URL = "https://manifest-editor.digirati.services"

[env.production]
vars.URL = "https://manifest-editor.digirati.services"
routes = [
    { pattern = "manifest-editor.digirati.services", custom_domain = true },
]
kv_namespaces = [
    { binding = "PREVIEW_KV", id = "9708730cddd545a68d255f11fe2d6b89" },
]

[env.preview]
vars.URL = "https://manifest-editor-preview.digirati.workers.dev"
kv_namespaces = [
    { binding = "PREVIEW_KV", id = "9708730cddd545a68d255f11fe2d6b89" },
]
