'$schema' = "node_modules/wrangler/config-schema.json"

name = "manifest-editor"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

route = { pattern = "manifest-editor.digirati.services/*", zone_name = "manifest-editor.digirati.services" }

main = ".open-next/worker.js"
assets.directory = ".open-next/assets"
assets.binding = "ASSETS"
account_id = "ae784157f30fd7164f22b075991c1caa"

[[kv_namespaces]]
id = "9708730cddd545a68d255f11fe2d6b89"
binding = "PREVIEW_KV"

[vars]
URL = "https://manifest-editor.digirati.services"

[env.preview.vars]
URL = "https://manifest-editor-preview.digirati.workers.dev"
