export * from "../editor-api/meta/behavior";
export * from "../editor-api/meta/descriptive";
export * from "../editor-api/meta/documentation";
export * from "../editor-api/meta/linking";
export * from "../editor-api/meta/references";
export * from "../editor-api/meta/resources";
export * from "../editor-api/meta/rights";
export * from "../editor-api/meta/structural";
export * from "../editor-api/meta/technical";
