/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ShellLazyImport = createFileRoute('/shell')()
const ExplorerLazyImport = createFileRoute('/explorer')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ShellLazyRoute = ShellLazyImport.update({
  path: '/shell',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shell.lazy').then((d) => d.Route))

const ExplorerLazyRoute = ExplorerLazyImport.update({
  path: '/explorer',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/explorer.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerLazyImport
      parentRoute: typeof rootRoute
    }
    '/shell': {
      id: '/shell'
      path: '/shell'
      fullPath: '/shell'
      preLoaderRoute: typeof ShellLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/explorer': typeof ExplorerLazyRoute
  '/shell': typeof ShellLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/explorer': typeof ExplorerLazyRoute
  '/shell': typeof ShellLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/explorer': typeof ExplorerLazyRoute
  '/shell': typeof ShellLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/explorer' | '/shell'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/explorer' | '/shell'
  id: '__root__' | '/' | '/about' | '/explorer' | '/shell'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ExplorerLazyRoute: typeof ExplorerLazyRoute
  ShellLazyRoute: typeof ShellLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ExplorerLazyRoute: ExplorerLazyRoute,
  ShellLazyRoute: ShellLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/explorer",
        "/shell"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/explorer": {
      "filePath": "explorer.lazy.tsx"
    },
    "/shell": {
      "filePath": "shell.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
